version: '2.1'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     # For local development of auditlog-enricher
     # - ADVERTISED_HOST_NAME=192.168.1.6
     - KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS=250
  order-management-db:
    image: debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=vegetablesdb
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"


  connect-es:
    image: debezium/connect-jdbc-es:1.0
    ports:
      - 8083:8083
    build:
      context: debezium-jdbc-es
    links:
      - kafka
      - order-management-db
      - elastic
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_source_connect_configs
      - OFFSET_STORAGE_TOPIC=my_source_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false

  order-management-service:
    image: debezium-examples/entitylog-order-management-service:${DEBEZIUM_VERSION}
    build:
      context: order-management-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
     - 8080:8080
    links:
     - order-management-db
    environment:
     - QUARKUS_DATASOURCE_URL=jdbc:postgresql://order-management-db:5432/vegetablesdb?currentSchema=inventory

  log-enricher:
    image: debezium-examples/entitylog-log-enricher:${DEBEZIUM_VERSION}
    build:
      context: log-enricher
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
     - 8082:8080
    links:
     - kafka
    environment:
     - QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS=kafka:9092

